# Generated by Django 5.0.9 on 2026-07-30 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPhotographerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('search_visibility', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('portfolio_interactions', models.IntegerField(default=0)),
                ('inquiries', models.IntegerField(default=0)),
                ('bookings_created', models.IntegerField(default=0)),
                ('bookings_accepted', models.IntegerField(default=0)),
                ('bookings_completed', models.IntegerField(default=0)),
                ('bookings_cancelled', models.IntegerField(default=0)),
                ('bookings_rejected', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('conversion_rate', models.FloatField(default=0.0, help_text='bookings_created / profile_views')),
                ('response_rate', models.FloatField(default=0.0, help_text='responded / requests received')),
                ('reviews_received', models.IntegerField(default=0)),
                ('avg_rating_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
            ],
            options={
                'db_table': 'daily_photographer_stats',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PlatformStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_buyers', models.IntegerField(default=0)),
                ('total_photographers', models.IntegerField(default=0)),
                ('approved_photographers', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('bookings_created', models.IntegerField(default=0)),
                ('bookings_completed', models.IntegerField(default=0)),
                ('bookings_cancelled', models.IntegerField(default=0)),
                ('bookings_expired', models.IntegerField(default=0)),
                ('gross_booking_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('marketplace_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('products_sold', models.IntegerField(default=0)),
                ('products_published', models.IntegerField(default=0)),
                ('reviews_posted', models.IntegerField(default=0)),
                ('avg_platform_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('cancellation_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'platform_stats',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('bookings_completed', models.IntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('HELD', 'Held')], db_index=True, default='PENDING', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('growth_percent', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'revenue_snapshots',
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.IntegerField(db_index=True, default=0)),
                ('clicked_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'search_query_logs',
            },
        ),
    ]
