# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('catalog', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyphotographerstat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stats', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='dailyphotographerstat',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='revenuesnapshot',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyphotographerstat',
            index=models.Index(fields=['photographer', '-date'], name='idx_dailystat_timeline'),
        ),
        migrations.AddIndex(
            model_name='dailyphotographerstat',
            index=models.Index(fields=['date'], name='idx_dailystat_by_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyphotographerstat',
            constraint=models.UniqueConstraint(fields=('photographer', 'date'), name='uniq_daily_stat_per_photog'),
        ),
        migrations.AddIndex(
            model_name='revenuesnapshot',
            index=models.Index(fields=['photographer', '-year', '-month'], name='idx_revenue_timeline'),
        ),
        migrations.AddConstraint(
            model_name='revenuesnapshot',
            constraint=models.UniqueConstraint(fields=('photographer', 'year', 'month'), name='uniq_revenue_per_month'),
        ),
        migrations.AddIndex(
            model_name='searchquerylog',
            index=models.Index(fields=['result_count', '-created_at'], name='idx_zero_results'),
        ),
    ]
