# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash on the day'), ('BANK_TRANSFER', 'Bank transfer'), ('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('ADVANCE_PAID', 'Advance paid'), ('FULLY_PAID', 'Fully paid'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=20)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='booking_receipts/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'booking_payments',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], max_length=16)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], max_length=16)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Booking status history',
                'db_table': 'booking_status_history',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.PositiveSmallIntegerField(default=4)),
                ('location_address', models.CharField(max_length=300)),
                ('location_city', models.CharField(db_index=True, max_length=80)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('travel_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('photographer_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=16)),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('special_requirements', models.TextField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='PENDING bookings auto-expire at this moment.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, max_length=500)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('BUYER_CHANGED_PLANS', 'Buyer changed plans'), ('BUYER_FOUND_ALTERNATIVE', 'Buyer found an alternative'), ('PHOTOGRAPHER_UNAVAILABLE', 'Photographer unavailable'), ('PRICE_DISAGREEMENT', 'Could not agree on price'), ('EVENT_CANCELLED', 'The event itself was cancelled'), ('PHOTOGRAPHER_SUSPENDED', 'Photographer suspended by admin'), ('WEATHER', 'Weather'), ('OTHER', 'Other')], max_length=32)),
                ('cancellation_note', models.TextField(blank=True, max_length=500)),
                ('has_review', models.BooleanField(db_index=True, default=False)),
                ('buyer_confirmed_completion', models.BooleanField(default=False)),
                ('photographer_marked_complete', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_cancelled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ('-created_at',),
            },
        ),
    ]
