# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalog', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(help_text='Copied from the service so analytics survive service deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.servicepackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_received', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='NULL means the change was made by the system (expiry job).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['buyer', 'status'], name='idx_booking_buyer_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['photographer', 'status'], name='idx_booking_photog_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='idx_booking_expiry_sweep'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['photographer', 'event_date'], name='idx_booking_calendar'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='idx_booking_recent'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('photographer', 'event_date', 'start_time'), name='uniq_active_booking_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='ck_booking_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='ck_booking_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['booking', 'created_at'], name='idx_bsh_timeline'),
        ),
    ]
