# Generated by Django 5.0.9 on 2026-07-30 18:28

import apps.core.utils
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('product_type', models.CharField(choices=[('LIGHTROOM_PRESET', 'Lightroom Preset'), ('PHOTOSHOP_TEMPLATE', 'Photoshop Template'), ('ALBUM_TEMPLATE', 'Album Template'), ('WEDDING_LUT', 'Wedding LUT'), ('VIDEO_EFFECT', 'Video Effect'), ('STOCK_PHOTO', 'Stock Photo'), ('OVERLAY', 'Overlay Pack'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('license_type', models.CharField(choices=[('PERSONAL', 'Personal use only'), ('COMMERCIAL', 'Commercial use'), ('EXTENDED', 'Extended commercial')], default='PERSONAL', max_length=16)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price, shown struck through to display a discount.', max_digits=10, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('thumbnail', models.ImageField(upload_to=apps.core.utils.UploadTo('products/thumbs'))),
                ('preview_images', models.JSONField(blank=True, default=list)),
                ('preview_video_url', models.URLField(blank=True)),
                ('file_count', models.PositiveSmallIntegerField(default=1)),
                ('total_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('compatible_with', models.JSONField(blank=True, default=list, help_text='e.g. ["Lightroom Classic 12+", "Lightroom Mobile"]')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Admin moderation gate — blocks copyright-infringing uploads.')),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sales_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('wishlist_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profiles.photographerprofile')),
            ],
            options={
                'db_table': 'digital_products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='marketplace.digitalproduct')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending payment'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('payment_method', models.CharField(default='WALLET', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('seller_earning', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('download_count', models.PositiveSmallIntegerField(default=0)),
                ('max_downloads', models.PositiveSmallIntegerField(default=5)),
                ('has_review', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.digitalproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='profiles.photographerprofile')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='private/products/%Y/%m/')),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256, so corrupted downloads can be detected.', max_length=64)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='marketplace.digitalproduct')),
            ],
            options={
                'db_table': 'product_files',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='marketplace.orderitem')),
                ('product_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='marketplace.productfile')),
            ],
            options={
                'db_table': 'download_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='digitalproduct',
            index=models.Index(fields=['is_published', 'is_approved', '-sales_count'], name='idx_product_browse'),
        ),
        migrations.AddIndex(
            model_name='digitalproduct',
            index=models.Index(fields=['product_type', 'price'], name='idx_product_type_price'),
        ),
        migrations.AddIndex(
            model_name='digitalproduct',
            index=models.Index(fields=['seller', 'is_published'], name='idx_product_by_seller'),
        ),
        migrations.AddConstraint(
            model_name='digitalproduct',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='ck_product_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_cart_item_per_user'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='idx_order_buyer_status'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('buyer', 'idempotency_key'), name='uniq_order_idempotency'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller', '-created_at'], name='idx_orderitem_seller'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='uniq_product_per_order'),
        ),
        migrations.AddIndex(
            model_name='downloadtoken',
            index=models.Index(fields=['token', 'expires_at'], name='idx_dl_token_lookup'),
        ),
    ]
