# Generated by Django 5.0.9 on 2026-07-31 07:11

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_partial_unique_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=apps.core.storage.PrivateMediaStorage(), upload_to='products/%Y/%m/'),
        ),
    ]
