# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(max_length=1000)),
                ('audience', models.CharField(choices=[('ALL', 'Everyone'), ('BUYERS', 'Buyers only'), ('PHOTOGRAPHERS', 'Photographers only'), ('CITY', 'Specific city')], default='ALL', max_length=20)),
                ('city_filter', models.CharField(blank=True, max_length=80)),
                ('send_push', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcasts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('BOOKING_REQUEST', 'New booking request'), ('BOOKING_ACCEPTED', 'Booking accepted'), ('BOOKING_REJECTED', 'Booking rejected'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('BOOKING_COMPLETED', 'Booking completed'), ('BOOKING_EXPIRED', 'Booking expired'), ('BOOKING_REMINDER', 'Upcoming shoot reminder'), ('PRODUCT_PURCHASED', 'Product purchased'), ('PRODUCT_SOLD', 'Your product sold'), ('PRODUCT_APPROVED', 'Product approved'), ('PRODUCT_REJECTED', 'Product rejected'), ('REVIEW_RECEIVED', 'New review received'), ('REVIEW_REPLIED', 'Photographer replied to your review'), ('REVIEW_REMINDER', 'Leave a review'), ('NEW_MESSAGE', 'New message'), ('ACCOUNT_APPROVED', 'Account approved'), ('ACCOUNT_REJECTED', 'Account rejected'), ('ACCOUNT_BLOCKED', 'Account blocked'), ('WALLET_CREDITED', 'Wallet credited'), ('PAYOUT_SENT', 'Payout sent'), ('ADMIN_MESSAGE', 'Message from SnapSphere'), ('PROMOTION', 'Promotion')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('action_screen', models.CharField(blank=True, max_length=60)),
                ('action_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who caused this — used for the avatar in the bell list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped by preference')], db_index=True, default='PENDING', max_length=16)),
                ('provider_response', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_deliveries',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('booking_updates', models.BooleanField(default=True)),
                ('chat_messages', models.BooleanField(default=True)),
                ('review_activity', models.BooleanField(default=True)),
                ('marketplace_activity', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=512)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WEB', 'Web')], max_length=16)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('failure_count', models.PositiveSmallIntegerField(default=0, help_text='Deactivated after repeated provider rejections.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_inbox'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='uniq_delivery_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='pushtoken',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='uniq_push_token'),
        ),
    ]
