# Generated by Django 5.0.9 on 2026-07-30 18:28

import apps.core.utils
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reviews_written', models.PositiveIntegerField(default=0)),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='interested_buyers', to='catalog.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer profile',
                'db_table': 'buyer_profiles',
            },
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('BANK', 'Bank transfer'), ('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash')], default='BANK', max_length=32)),
                ('transaction_reference', models.CharField(max_length=100)),
                ('receipt_image', models.ImageField(upload_to=apps.core.utils.UploadTo('receipts'))),
                ('status', models.CharField(choices=[('PENDING', 'Pending verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_topups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'topup_requests',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_credited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_debited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_type', models.CharField(choices=[('TOPUP', 'Top-up'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('PAYOUT', 'Payout to photographer'), ('EARNING', 'Sale earning'), ('ADJUSTMENT', 'Admin adjustment')], db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Related order/booking identifier.', max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_actions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='profiles.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
        migrations.CreateModel(
            name='PhotographerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=140)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('bio', models.TextField(blank=True, max_length=2000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('covers'))),
                ('years_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('equipment', models.TextField(blank=True, max_length=1000)),
                ('languages', models.CharField(blank=True, default='English, Urdu', max_length=200)),
                ('base_price', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text="Starting price in PKR — the 'from Rs X' shown on listings.", max_digits=12)),
                ('travel_available', models.BooleanField(default=True)),
                ('service_radius_km', models.PositiveSmallIntegerField(default=50)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True)),
                ('cnic_number', models.CharField(blank=True, max_length=20)),
                ('cnic_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('verification'))),
                ('is_verified', models.BooleanField(default=False, help_text='Blue-tick badge shown on the profile.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_accepting_bookings', models.BooleanField(db_index=True, default=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('bayesian_rating', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), help_text='Rating smoothed toward the platform mean; used for ranking.', max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('completed_bookings', models.PositiveIntegerField(default=0)),
                ('cancelled_bookings', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='completed / (completed + cancelled + rejected)', max_digits=4)),
                ('avg_response_time_hours', models.DecimalField(decimal_places=2, default=Decimal('24.00'), help_text='Hours to respond to a booking request. LOWER IS BETTER — the ranking model inverts this before use.', max_digits=6)),
                ('portfolio_score', models.PositiveIntegerField(default=0, help_text='Composite engagement score (0-999) from portfolio quality and interaction volume.')),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('search_appearances', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_photographers', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='photographers', to='catalog.category')),
                ('specializations', models.ManyToManyField(blank=True, related_name='photographers', to='catalog.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photographer profile',
                'db_table': 'photographer_profiles',
                'indexes': [models.Index(fields=['is_approved', 'is_accepting_bookings', '-bayesian_rating'], name='idx_photog_discovery'), models.Index(fields=['base_price'], name='idx_photog_price'), models.Index(fields=['is_featured', '-bayesian_rating'], name='idx_photog_featured'), models.Index(fields=['-completed_bookings'], name='idx_photog_popularity')],
            },
        ),
        migrations.AddConstraint(
            model_name='photographerprofile',
            constraint=models.CheckConstraint(check=models.Q(('avg_rating__gte', 0), ('avg_rating__lte', 5)), name='ck_photog_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='photographerprofile',
            constraint=models.CheckConstraint(check=models.Q(('base_price__gte', 0)), name='ck_photog_price_positive'),
        ),
        migrations.AddIndex(
            model_name='topuprequest',
            index=models.Index(fields=['status', '-created_at'], name='idx_topup_queue'),
        ),
        migrations.AddConstraint(
            model_name='topuprequest',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='ck_topup_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='topuprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('transaction_reference',), name='uniq_approved_txn_reference'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='ck_wallet_no_overdraft'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='idx_wallet_txn_recent'),
        ),
    ]
