# Generated by Django 5.0.9 on 2026-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_partial_unique_topup_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerprofile',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
