# Generated by Django 5.0.9 on 2026-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MORE_INFO', 'More information required')], db_index=True, default='PENDING', max_length=16)),
                ('submitted_data', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, max_length=1000)),
                ('rejection_reason', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('USER_BLOCKED', 'User blocked'), ('USER_UNBLOCKED', 'User unblocked'), ('USER_DELETED', 'User deleted'), ('PHOTOGRAPHER_APPROVED', 'Photographer approved'), ('PHOTOGRAPHER_REJECTED', 'Photographer rejected'), ('BOOKING_FORCE_CANCELLED', 'Booking force-cancelled'), ('PRODUCT_APPROVED', 'Product approved'), ('PRODUCT_REMOVED', 'Product removed'), ('REVIEW_HIDDEN', 'Review hidden'), ('WALLET_ADJUSTED', 'Wallet adjusted'), ('TOPUP_APPROVED', 'Top-up approved'), ('TOPUP_REJECTED', 'Top-up rejected'), ('SETTING_CHANGED', 'Platform setting changed'), ('CATEGORY_CHANGED', 'Category changed'), ('BROADCAST_SENT', 'Broadcast sent'), ('MODEL_PROMOTED', 'ML model promoted')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_label', models.CharField(blank=True, help_text='Human-readable snapshot, so the log stays readable even after the target row is anonymised or removed.', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=40)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ModerationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('REVIEW', 'Review'), ('PORTFOLIO_IMAGE', 'Portfolio image'), ('PRODUCT', 'Digital product'), ('MESSAGE', 'Chat message'), ('PROFILE', 'Profile')], db_index=True, max_length=40)),
                ('object_id', models.BigIntegerField(db_index=True)),
                ('reason', models.CharField(choices=[('INAPPROPRIATE', 'Inappropriate content'), ('COPYRIGHT', 'Copyright infringement'), ('SPAM', 'Spam'), ('FAKE', 'Fake or misleading'), ('HARASSMENT', 'Harassment'), ('OFF_PLATFORM', 'Attempting to take the deal off-platform'), ('OTHER', 'Other')], max_length=24)),
                ('detail', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Under review'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'moderation_flags',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('FLOAT', 'Float'), ('BOOL', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=16)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('group', models.CharField(db_index=True, default='general', help_text='Groups settings into tabs in the admin dashboard.', max_length=40)),
                ('is_public', models.BooleanField(default=False, help_text='Exposed to the mobile app via /settings/public/.')),
            ],
            options={
                'db_table': 'platform_settings',
                'ordering': ('group', 'key'),
            },
        ),
    ]
