# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalog', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('ranker', 'Content ranker'), ('cf', 'Collaborative filter'), ('sentiment', 'Sentiment classifier'), ('product_ranker', 'Product ranker')], db_index=True, max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('algorithm', models.CharField(blank=True, max_length=80)),
                ('artifact_path', models.CharField(max_length=300)),
                ('feature_order', models.JSONField(blank=True, default=list)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='e.g. {"rmse": 0.41, "mae": 0.32, "precision_at_10": 0.68}')),
                ('training_rows', models.IntegerField(default=0)),
                ('training_duration_seconds', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'model_versions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PhotographerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('bayesian_rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('years_experience', models.IntegerField(default=0)),
                ('bookings_success_rate', models.FloatField(default=0.0)),
                ('response_time_hours', models.FloatField(default=24.0)),
                ('portfolio_score', models.IntegerField(default=0)),
                ('base_price', models.FloatField(default=0.0)),
                ('completed_bookings', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('portfolio_image_count', models.IntegerField(default=0)),
                ('response_speed_score', models.FloatField(default=0.0, help_text='1 / (1 + hours). INVERTED because low response time is good — feeding raw hours would train the model to prefer slow photographers.')),
                ('popularity_score', models.FloatField(default=0.0, help_text='log1p(completed_bookings) normalised 0-1.')),
                ('engagement_rate', models.FloatField(default=0.0, help_text='bookings / profile_views.')),
                ('recency_score', models.FloatField(default=0.0, help_text='Decays with days since last completed booking.')),
                ('price_percentile', models.FloatField(default=0.5, help_text='Where this price sits among all photographers.')),
                ('sentiment_score', models.FloatField(default=0.5, help_text='Mean predicted sentiment across their reviews.')),
                ('is_new_photographer', models.BooleanField(default=False, help_text='< 30 days old. Qualifies for a guaranteed exploration slot.')),
                ('quality_score', models.FloatField(db_index=True, default=0.0)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'photographer_features',
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(help_text='1-based rank shown.')),
                ('score', models.FloatField()),
                ('content_score', models.FloatField(default=0.0)),
                ('collab_score', models.FloatField(default=0.0)),
                ('business_score', models.FloatField(default=0.0)),
                ('strategy', models.CharField(choices=[('HYBRID', 'Hybrid'), ('CONTENT', 'Content-based'), ('COLLABORATIVE', 'Collaborative'), ('POPULARITY', 'Popularity fallback'), ('EXPLORATION', 'Exploration slot')], db_index=True, default='HYBRID', max_length=24)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, help_text='Human-readable explanation shown in the app.', max_length=200)),
                ('was_clicked', models.BooleanField(db_index=True, default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('led_to_booking', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'recommendation_events',
            },
        ),
        migrations.CreateModel(
            name='SeasonalDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('avg_bookings', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('demand_score', models.IntegerField(default=50, help_text='0-100 relative demand index.')),
            ],
            options={
                'db_table': 'seasonal_demand',
                'ordering': ('month',),
            },
        ),
        migrations.CreateModel(
            name='BuyerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Profile view'), ('CLICK', 'Card click'), ('PORTFOLIO', 'Portfolio interaction'), ('SEARCH', 'Appeared in search'), ('INQUIRY', 'Message sent'), ('WISHLIST', 'Added to wishlist'), ('BOOKING', 'Booking created'), ('COMPLETED', 'Booking completed')], db_index=True, max_length=16)),
                ('weight', models.FloatField(default=1.0)),
                ('search_keyword', models.CharField(blank=True, max_length=120)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='catalog.category')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_interactions', to='profiles.photographerprofile')),
            ],
            options={
                'db_table': 'buyer_interactions',
            },
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_model_version'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='uniq_active_model_per_name'),
        ),
        migrations.AddField(
            model_name='photographerfeature',
            name='photographer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='recommendationevent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='recommendationevent',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationevent',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='recommendations.modelversion'),
        ),
        migrations.AddField(
            model_name='recommendationevent',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='seasonaldemand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_demand', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='buyerinteraction',
            index=models.Index(fields=['buyer', 'photographer'], name='idx_interaction_pair'),
        ),
        migrations.AddIndex(
            model_name='buyerinteraction',
            index=models.Index(fields=['-created_at'], name='idx_interaction_recent'),
        ),
        migrations.AddIndex(
            model_name='photographerfeature',
            index=models.Index(fields=['-quality_score'], name='idx_feature_quality'),
        ),
        migrations.AddIndex(
            model_name='recommendationevent',
            index=models.Index(fields=['buyer', '-created_at'], name='idx_recevent_by_buyer'),
        ),
        migrations.AddIndex(
            model_name='recommendationevent',
            index=models.Index(fields=['strategy', 'was_clicked'], name='idx_recevent_ctr'),
        ),
        migrations.AddIndex(
            model_name='recommendationevent',
            index=models.Index(fields=['-created_at'], name='idx_recevent_recent'),
        ),
        migrations.AddConstraint(
            model_name='seasonaldemand',
            constraint=models.UniqueConstraint(fields=('month', 'category'), name='uniq_seasonal_month_category'),
        ),
    ]
