# Generated by Django 5.0.9 on 2026-07-30 18:28

import apps.core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('albums'))),
                ('shoot_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('client_name', models.CharField(blank=True, help_text='Only shown if the client consented.', max_length=120)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='catalog.category')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='profiles.photographerprofile')),
            ],
            options={
                'db_table': 'portfolio_albums',
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=apps.core.utils.UploadTo('portfolio'))),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('portfolio/thumbs'))),
                ('image_large', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('portfolio/large'))),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility description.', max_length=200)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='portfolio.portfolioalbum')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_images', to='catalog.category')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='profiles.photographerprofile')),
            ],
            options={
                'db_table': 'portfolio_images',
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='portfolio.portfolioimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_image_likes',
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('provider', models.CharField(choices=[('UPLOADED', 'Uploaded to SnapSphere'), ('YOUTUBE', 'YouTube'), ('VIMEO', 'Vimeo')], default='UPLOADED', max_length=16)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('videos'))),
                ('external_url', models.URLField(blank=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('videos/posters'))),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='portfolio.portfolioalbum')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_videos', to='profiles.photographerprofile')),
            ],
            options={
                'db_table': 'portfolio_videos',
                'ordering': ('display_order', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='portfolioalbum',
            index=models.Index(fields=['photographer', 'is_public'], name='idx_album_by_photog'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['photographer', 'is_featured'], name='idx_image_featured'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['album', 'display_order'], name='idx_image_in_album'),
        ),
        migrations.AddConstraint(
            model_name='portfolioimagelike',
            constraint=models.UniqueConstraint(fields=('image', 'user'), name='uniq_like_per_user_image'),
        ),
        migrations.AddConstraint(
            model_name='portfoliovideo',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('provider', 'UPLOADED'), ('video_file__isnull', False)), models.Q(models.Q(('provider', 'UPLOADED'), _negated=True), models.Q(('external_url', ''), _negated=True)), _connector='OR'), name='ck_video_source_present'),
        ),
    ]
