# Generated by Django 5.0.9 on 2026-07-30 18:28

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name used by the mobile app.', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('categories'))),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('photographer_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('features', models.JSONField(blank=True, default=list)),
                ('duration_hours', models.PositiveSmallIntegerField(default=4)),
                ('edited_photos_count', models.PositiveIntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'service_packages',
                'ordering': ('display_order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'specializations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('services'))),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('pricing_unit', models.CharField(choices=[('FIXED', 'Fixed package price'), ('PER_HOUR', 'Per hour'), ('PER_DAY', 'Per day'), ('PER_EVENT', 'Per event')], default='FIXED', max_length=16)),
                ('min_hours', models.PositiveSmallIntegerField(default=1)),
                ('duration_hours', models.PositiveSmallIntegerField(default=4)),
                ('edited_photos_count', models.PositiveIntegerField(default=0)),
                ('raw_photos_included', models.BooleanField(default=False)),
                ('delivery_days', models.PositiveSmallIntegerField(default=14)),
                ('includes', models.JSONField(blank=True, default=list, help_text='List of bullet points, e.g. ["2 photographers", "Drone shots"]')),
                ('advance_payment_percent', models.PositiveSmallIntegerField(default=30)),
                ('max_travel_km', models.PositiveSmallIntegerField(default=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(help_text='PROTECT: a category with live services cannot be deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.category')),
            ],
            options={
                'db_table': 'services',
                'ordering': ('display_order', 'price'),
            },
        ),
    ]
