# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specializations', to='catalog.category'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['photographer', 'is_active'], name='idx_service_by_photog'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active', 'price'], name='idx_service_browse'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='ck_service_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('advance_payment_percent__lte', 100)), name='ck_service_advance_percent'),
        ),
        migrations.AddConstraint(
            model_name='servicepackage',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='uniq_package_name_per_service'),
        ),
        migrations.AddConstraint(
            model_name='servicepackage',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', Decimal('0'))), name='ck_package_price_positive'),
        ),
    ]
