# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        ('bookings', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityrule',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='blackoutdate',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_dates', to='profiles.photographerprofile'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_slot', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='profiles.photographerprofile'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.UniqueConstraint(fields=('photographer', 'weekday'), name='uniq_rule_per_weekday'),
        ),
        migrations.AddConstraint(
            model_name='availabilityrule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='ck_rule_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='blackoutdate',
            index=models.Index(fields=['photographer', 'start_date', 'end_date'], name='idx_blackout_lookup'),
        ),
        migrations.AddConstraint(
            model_name='blackoutdate',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='ck_blackout_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['photographer', 'date', 'is_booked'], name='idx_slot_availability'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('photographer', 'date', 'start_time'), name='uniq_slot_per_photog_datetime'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='ck_slot_end_after_start'),
        ),
    ]
