# Generated by Django 5.0.9 on 2026-07-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='profiles.photographerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='marketplace.digitalproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist_items',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_wishlist_by_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('photographer__isnull', False), ('product__isnull', True)), models.Q(('photographer__isnull', True), ('product__isnull', False)), _connector='OR'), name='ck_wishlist_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('photographer__isnull', False)), fields=('user', 'photographer'), name='uniq_wishlist_photographer'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='uniq_wishlist_product'),
        ),
    ]
