# Generated by Django 5.0.9 on 2026-07-30 18:28

import apps.core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('marketplace', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_professionalism', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_communication', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_punctuality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=140)),
                ('comment', models.TextField(blank=True, max_length=3000)),
                ('sentiment', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], db_index=True, help_text='Predicted by the TF-IDF + LogisticRegression model trained on yelp.csv. The labels in reviews_feedback.csv are noise and are deliberately not used.', max_length=16)),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=3, help_text='Model confidence 0.000-1.000.', max_digits=4, null=True)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('hidden_reason', models.CharField(blank=True, max_length=200)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_count', models.PositiveSmallIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('booking', models.OneToOneField(help_text='One review per completed booking. This IS the anti-fraud control.', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='bookings.booking')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.photographerprofile')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_helpful_votes',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.core.utils.UploadTo('reviews'))),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.UploadTo('reviews/thumbs'))),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review')),
            ],
            options={
                'db_table': 'review_images',
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=2000)),
                ('is_edited', models.BooleanField(default=False)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to='profiles.photographerprofile')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.review')),
            ],
            options={
                'db_table': 'review_replies',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=140)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('is_hidden', models.BooleanField(default=False)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='marketplace.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.digitalproduct')),
            ],
            options={
                'db_table': 'product_reviews',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'is_hidden', '-created_at'], name='idx_prodreview_list')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['photographer', 'is_hidden', '-created_at'], name='idx_review_public_list'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['photographer', '-rating'], name='idx_review_by_rating'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['buyer', '-created_at'], name='idx_review_by_buyer'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='ck_review_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpful',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='uniq_helpful_vote_per_user'),
        ),
    ]
