# Generated by Django 5.0.9 on 2026-09-16 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_partial_unique_slot'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='One review per completed booking, or null for direct reviews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.booking'),
        ),
    ]
